version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gameplus_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123@
      POSTGRES_DB: gameplus_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
